version: "3.8"

services:
  shadcn-mcp:
    container_name: shadcn-mcp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6728:6728"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6728/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
